/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppStatistics {
  'totalChannelsCreated' : bigint,
  'totalMessagesSent' : bigint,
  'totalRegisteredUsers' : bigint,
  'totalXpGained' : bigint,
}
export interface Attachment {
  'id' : string,
  'file' : ExternalBlob,
  'type' : AttachmentType,
}
export type AttachmentType = { 'gif' : null } |
  { 'voice' : null } |
  { 'document' : null } |
  { 'image' : null };
export interface Channel {
  'creator' : Principal,
  'allowRandomJoin' : boolean,
  'name' : string,
  'createdAt' : Time,
  'maxMembers' : [] | [bigint],
  'isPrivate' : boolean,
}
export interface ChannelWithMembers {
  'creator' : Principal,
  'allowRandomJoin' : boolean,
  'name' : string,
  'createdAt' : Time,
  'memberCount' : bigint,
  'maxMembers' : [] | [bigint],
  'isPrivate' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'channel' : string,
  'attachments' : Array<Attachment>,
}
export type Time = bigint;
export interface UserProfile {
  'xp' : bigint,
  'username' : string,
  'level' : bigint,
  'joinedChannels' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChannel' : ActorMethod<[string, boolean], undefined>,
  'getAccessibleChannels' : ActorMethod<[], Array<ChannelWithMembers>>,
  'getCallerUserLevelProgress' : ActorMethod<[], [bigint, number]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelDetails' : ActorMethod<[string], [] | [Channel]>,
  'getChannelMemberLimit' : ActorMethod<[string], [] | [bigint]>,
  'getChannelMessages' : ActorMethod<[string], Array<Message>>,
  'getGlobalAppStatistics' : ActorMethod<[], AppStatistics>,
  'getRandomJoinEnabled' : ActorMethod<[string], boolean>,
  'getUserChannels' : ActorMethod<[Principal], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserXPAndLevel' : ActorMethod<[], [bigint, bigint]>,
  'getUsername' : ActorMethod<[Principal], [] | [string]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isChannelAdmin' : ActorMethod<[string], boolean>,
  'joinChannel' : ActorMethod<[string], undefined>,
  'joinRandomChannel' : ActorMethod<[], string>,
  'leaveChannel' : ActorMethod<[string, [] | [boolean]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string, Array<Attachment>], undefined>,
  'setChannelMaxMembers' : ActorMethod<[string, [] | [bigint]], undefined>,
  'setRandomJoinEnabled' : ActorMethod<[string, boolean], undefined>,
  'setUsername' : ActorMethod<[string], undefined>,
  'verifyChannelAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];