/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ChannelWithMembers = IDL.Record({
  'creator' : IDL.Principal,
  'allowRandomJoin' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'memberCount' : IDL.Nat,
  'maxMembers' : IDL.Opt(IDL.Nat),
  'isPrivate' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'level' : IDL.Nat,
  'joinedChannels' : IDL.Vec(IDL.Text),
});
export const Channel = IDL.Record({
  'creator' : IDL.Principal,
  'allowRandomJoin' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'maxMembers' : IDL.Opt(IDL.Nat),
  'isPrivate' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AttachmentType = IDL.Variant({
  'gif' : IDL.Null,
  'voice' : IDL.Null,
  'document' : IDL.Null,
  'image' : IDL.Null,
});
export const Attachment = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'type' : AttachmentType,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'channel' : IDL.Text,
  'attachments' : IDL.Vec(Attachment),
});
export const AppStatistics = IDL.Record({
  'totalChannelsCreated' : IDL.Nat,
  'totalMessagesSent' : IDL.Nat,
  'totalRegisteredUsers' : IDL.Nat,
  'totalXpGained' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannel' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'getAccessibleChannels' : IDL.Func(
      [],
      [IDL.Vec(ChannelWithMembers)],
      ['query'],
    ),
  'getCallerUserLevelProgress' : IDL.Func(
      [],
      [IDL.Nat, IDL.Float64],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelDetails' : IDL.Func([IDL.Text], [IDL.Opt(Channel)], ['query']),
  'getChannelMemberLimit' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getChannelMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getGlobalAppStatistics' : IDL.Func([], [AppStatistics], ['query']),
  'getRandomJoinEnabled' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getUserChannels' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserXPAndLevel' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getUsername' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isChannelAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinChannel' : IDL.Func([IDL.Text], [], []),
  'joinRandomChannel' : IDL.Func([], [IDL.Text], []),
  'leaveChannel' : IDL.Func([IDL.Text, IDL.Opt(IDL.Bool)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Attachment)], [], []),
  'setChannelMaxMembers' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [], []),
  'setRandomJoinEnabled' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
  'verifyChannelAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChannelWithMembers = IDL.Record({
    'creator' : IDL.Principal,
    'allowRandomJoin' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'memberCount' : IDL.Nat,
    'maxMembers' : IDL.Opt(IDL.Nat),
    'isPrivate' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'level' : IDL.Nat,
    'joinedChannels' : IDL.Vec(IDL.Text),
  });
  const Channel = IDL.Record({
    'creator' : IDL.Principal,
    'allowRandomJoin' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'maxMembers' : IDL.Opt(IDL.Nat),
    'isPrivate' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AttachmentType = IDL.Variant({
    'gif' : IDL.Null,
    'voice' : IDL.Null,
    'document' : IDL.Null,
    'image' : IDL.Null,
  });
  const Attachment = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'type' : AttachmentType,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'channel' : IDL.Text,
    'attachments' : IDL.Vec(Attachment),
  });
  const AppStatistics = IDL.Record({
    'totalChannelsCreated' : IDL.Nat,
    'totalMessagesSent' : IDL.Nat,
    'totalRegisteredUsers' : IDL.Nat,
    'totalXpGained' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannel' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'getAccessibleChannels' : IDL.Func(
        [],
        [IDL.Vec(ChannelWithMembers)],
        ['query'],
      ),
    'getCallerUserLevelProgress' : IDL.Func(
        [],
        [IDL.Nat, IDL.Float64],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelDetails' : IDL.Func([IDL.Text], [IDL.Opt(Channel)], ['query']),
    'getChannelMemberLimit' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getChannelMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getGlobalAppStatistics' : IDL.Func([], [AppStatistics], ['query']),
    'getRandomJoinEnabled' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getUserChannels' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserXPAndLevel' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getUsername' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isChannelAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinChannel' : IDL.Func([IDL.Text], [], []),
    'joinRandomChannel' : IDL.Func([], [IDL.Text], []),
    'leaveChannel' : IDL.Func([IDL.Text, IDL.Opt(IDL.Bool)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Attachment)], [], []),
    'setChannelMaxMembers' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [], []),
    'setRandomJoinEnabled' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
    'verifyChannelAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };